# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
dist: ./build/release
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: server
    main: ./cmd/main.go
    ldflags:
      - -s -w -X main.release={{.Version}} -X main.commit={{.Commit}} -X main.repo={{.GitURL}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macOS
    wrap_in_directory: true
    format: tar.gz
    format_overrides:  # archive as zip on Windows
      - goos: windows
        format: zip
    files:
      - LICENCE*
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
