name: 'Uptoc Action'
description: 'Publish your static files, support oss,cos,qiniu,aws s3,google storage'
author: 'saltbo <saltbo@foxmail.com>'
branding:
  color: 'blue'
  icon: 'arrow-up-circle'

inputs:
  driver:
    description: 'specify driver for the cloud platform'
    required: true
  region:
    description: 'specify region of the cloud platform'
    required: true
  bucket:
    description: 'specify bucket name of the cloud platform'
    required: true
  exclude:
    description: 'specify exclude the given comma separated directories'
    required: false
  dist:
    description: 'specify dist of the local directory'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
